
services:

  dns:
    build: 
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/udp"
   

  web01:
    build:
      context: ./web
      dockerfile: Dockerfile
    
    container_name: web01
   #ports:
     #  - "80:80/tcp"
  web01a:
    build:
      context: ./web
      dockerfile: Dockerfile
     
    container_name: web01a
    #ports:
     #  - "80:80/tcp"
    

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    ports:
       - "80:80/tcp"
    

  web02:
   build:
     context: ./web02
     dockerfile: Dockerfile
   container_name: web02
    #ports:
     #  - "80:80/tcp"

  web03:
   build:
     context: ./web03
     dockerfile: Dockerfile
   container_name: web03
    #ports:
     #  - "80:80/tcp"
  volumes:
   - ./proxy/certs:/etc/nginx/ssl